name: misskey-kit
services:

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - ./etc/docker.env
    networks:
      - external_network

  # A load balancer to enable non-disruptive replacement of web containers
  lb:
    image: jwilder/nginx-proxy:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${COMPOSE_PROJECT_DIR:-.}/etc/nginx-custom.conf:/etc/nginx/conf.d/nginx-custom.conf:ro
    ports: ["80:80"]
    networks:
      - external_network

  web:
    image: misskey/misskey:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      lb:
        condition: service_started
    networks:
      - internal_network
      - external_network
    volumes:
      - ${COMPOSE_PROJECT_DIR:-.}/etc/misskey-default.yml:/misskey/.config/default.yml:ro
      - misskey-data:/misskey/files
    environment:
      - VIRTUAL_HOST=~^.*$$  # marker for lb
      - VIRTUAL_PORT=3000  # target port for lb

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    build: 
      context: pg_bigm
    networks:
      - internal_network
    env_file:
      - ./etc/docker.env
    volumes:
      - ${COMPOSE_PROJECT_DIR:-.}/etc/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
  
  ai:
    build: 
      context: ai
      args:
        - enable_mecab=1
    networks:
      - external_network
    env_file:
      - ./etc/docker.env
    volumes:
      - ai-data:/ai/data/

  cron:
    build:
      context: cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COMPOSE_PROJECT_DIR:-.}/:/misskey/:ro
    environment:
      - COMPOSE_PROJECT_DIR=${COMPOSE_PROJECT_DIR:-${PWD:-.}}
    network_mode:
      - external_network  # needs internet access to perform git pull or docker pull

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  db-data:
  redis-data:
  misskey-data:
  ai-data:
